### ISSUE TITLE
Fix text

### ISSUE THREAD

**Issue by RyanZim** [pajasevi/UnCSS-Online#10]
Site says:

> This site uses 2 threads of your CPU power to mine Monero digital currency using Coinhive to cover costs of running this service.

This was changed in https://github.com/pajasevi/UnCSS-Online/commit/851876fa769dd84037f9b06c59711a4359500e75, text should be updated.

Oh, and BTW, nice to meet another fellow cryptocurrency fan. :smile:

**Comment by pajasevi** [comment]
Thanks for the notice. I updated the text and also added the option to disable the miner. ❤️
