### ISSUE TITLE
 Error Gateway Timeout

### ISSUE THREAD

**Issue by pricelessbrewing** [pajasevi/UnCSS-Online#6]
Sorry to bother you, I was the one on the unCSS repo that was trying to use the server and I'm getting a gateway timeout error. Is this confirmed working with a test, or just the sites back up? Maybe something not supported is in my files that's breaking it?

https://raw.githubusercontent.com/pricelessbrewing/BiabCalc/master/index.html

https://raw.githubusercontent.com/pricelessbrewing/BiabCalc/master/CSS/Main.css

PS: I know everything is a mess and probably tons of errors and sloppy code in there. I'm still learning

**Comment by pajasevi** [comment]
Hmm weird, I had to restart the server and now it works.

Tip: Delete all links to JS files from HTML when using uncss-online (uncss has some errors if they are included) I should fix that in the future.

Thanks for reporting!
